gui:
  showIcons: true
  nerdFontsVersion: "3"
  showRandomTip: false
  showCommandLog: false
  border: rounded
  theme:
    activeBorderColor:
      - "#61afef"
      - bold
    inactiveBorderColor:
      - "#3b4048"
    selectedLineBgColor:
      - "#2c313a"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  autoFetch: true
  autoRefresh: true
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
os:
  editPreset: nvim
keybinding:
  universal:
    quit: q
