repos:
  - repo: https://github.com/oxsecurity/megalinter
    rev: v9.3.0
    hooks:
      - id: megalinter-incremental
        stages: [pre-commit]
      - id: megalinter-full
        stages: [pre-push]

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.22.0
    hooks:
      - id: zizmor

  - repo: local
    hooks:
      - id: pytest-damage-control
        name: pytest (damage-control)
        entry: >-
          bash -c
          'cd home/dot_claude/exact_hooks/damage-control &&
          uv run --with pytest --with pytest-xdist --with pyyaml pytest tests/ -v -n auto'
        language: system
        pass_filenames: false
        files: ^home/dot_claude/exact_hooks/damage-control/
