"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
scan_timeout = 30
command_timeout = 500
format = '$all$fill$time$line_break$character'

[fill]
symbol = ' '

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[directory]
truncation_length = 3
truncate_to_repo = true
read_only = " 󰌾"

[git_branch]
symbol = " "
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_commit]
tag_symbol = '  '

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
conflicted = '=${count}'
deleted = '✘${count}'
modified = '!${count}'
staged = '+${count}'
untracked = '?${count}'
stashed = '*${count}'
renamed = '»${count}'

[cmd_duration]
min_time = 2_000
show_milliseconds = false
format = '[$duration](bold yellow) '

[status]
disabled = false

[time]
disabled = false
format = '[$time]($style)'

# Disabled modules
[aws]
disabled = true

[gcloud]
disabled = true

[azure]
disabled = true

[kubernetes]
disabled = true
