[settings.npm]
package_manager = "bun"

[tools]
bun = "1.3.9"
go = "1.26.0"
node = "24.13.1"
ruby = "4.0.1"
rust = "1.93.1"
"npm:@os-eco/mulch-cli" = "0.6.3"
"npm:@os-eco/seeds-cli" = "0.2.4"
"npm:@os-eco/canopy-cli" = "0.2.0"
"npm:@os-eco/overstory-cli" = "0.7.5"
