name: lint

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run shellcheck
        run: find . -name '*.sh' -not -path './.git/*' -exec shellcheck {} +

      - name: Run shfmt
        run: |
          go install mvdan.cc/sh/v3/cmd/shfmt@v3.12.0
          find . -name '*.sh' -not -path './.git/*' -exec shfmt -d {} +

      - name: Run actionlint
        shell: bash
        run: |
          bash <(curl -sSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint

      - name: Run ruff
        run: |
          pip install ruff
          ruff check .
          ruff format --check .

      - name: Run selene
        run: |
          curl -sSL https://github.com/Kampfkarren/selene/releases/download/0.30.0/selene-light-0.30.0-linux-amd64.zip -o selene.zip
          unzip selene.zip
          ./selene .

      - name: Run stylua
        run: |
          curl -sSL https://github.com/JohnnyMorganz/StyLua/releases/download/v2.3.1/stylua-linux-x86_64.zip -o stylua.zip
          unzip stylua.zip
          ./stylua --check .

      - name: Run markdownlint
        run: npx markdownlint-cli2
